import type { IBookCardProps } from "@/types";

export const books: IBookCardProps[] = [
  {
    id: 1,
    year: 2021,
    title: "La Sombra del Viento",
    author: "Carlos Ruiz Zafón",
    rating: 4.8,
    totalLikes: 1200,
    coverImage: "https://m.media-amazon.com/images/I/51+9U3V-VlL._SX376_BO1,204,203,200_.jpg",
    genre: ["Ficción", "Misterio"],
  },
  {
    id: 2,
    year: 2019,
    title: "Cien Años de Soledad",
    author: "Gabriel García Márquez",
    rating: 4.9,
    totalLikes: 1800,
    coverImage: "https://m.media-amazon.com/images/I/41P1kQlVJdL._SX323_BO1,204,203,200_.jpg",
    genre: ["Realismo Mágico", "Ficción"],
  },
  {
    id: 3,
    year: 2018,
    title: "El Código Da Vinci",
    author: "Dan Brown",
    rating: 4.5,
    totalLikes: 2500,
    coverImage: "https://m.media-amazon.com/images/I/51n04bKPq+L._SX320_BO1,204,203,200_.jpg",
    genre: ["Thriller", "Misterio"],
  },
  {
    id: 4,
    year: 2020,
    title: "El Alquimista",
    author: "Paulo Coelho",
    rating: 4.6,
    totalLikes: 3000,
    coverImage: "https://m.media-amazon.com/images/I/71cDh75W6rL._AC_UL320_.jpg",
    genre: ["Ficción", "Aventura"],
  },
  {
    id: 5,
    year: 2022,
    title: "1984",
    author: "George Orwell",
    rating: 4.7,
    totalLikes: 2200,
    coverImage: "https://m.media-amazon.com/images/I/71zK+CrI-kL._AC_SY679_.jpg",
    genre: ["Distopía", "Política"],
  },
  {
    id: 6,
    year: 2015,
    title: "El Juego de Ender",
    author: "Orson Scott Card",
    rating: 4.4,
    totalLikes: 1500,
    coverImage: "https://m.media-amazon.com/images/I/51gJ8Cgbk0L._SX314_BO1,204,203,200_.jpg",
    genre: ["Ciencia Ficción", "Aventura"],
  },
  {
    id: 7,
    year: 2017,
    title: "Los Miserables",
    author: "Victor Hugo",
    rating: 4.8,
    totalLikes: 2800,
    coverImage: "https://m.media-amazon.com/images/I/51-RoC0pnML._SX314_BO1,204,203,200_.jpg",
    genre: ["Drama", "Histórico"],
  },
  {
    id: 8,
    year: 2014,
    title: "Harry Potter y la Piedra Filosofal",
    author: "J.K. Rowling",
    rating: 4.9,
    totalLikes: 5000,
    coverImage: "https://m.media-amazon.com/images/I/91HHd3zycbL._AC_SY679_.jpg",
    genre: ["Fantasía", "Aventura"],
  },
  {
    id: 9,
    year: 2011,
    title: "El Gran Gatsby",
    author: "F. Scott Fitzgerald",
    rating: 4.3,
    totalLikes: 1300,
    coverImage: "https://m.media-amazon.com/images/I/81p2jwMw27L._AC_SY679_.jpg",
    genre: ["Ficción", "Clásico"],
  },
  {
    id: 10,
    year: 2016,
    title: "Matar a un Ruiseñor",
    author: "Harper Lee",
    rating: 4.8,
    totalLikes: 3000,
    coverImage: "https://m.media-amazon.com/images/I/91h5xO8Yr5L._AC_SY679_.jpg",
    genre: ["Drama", "Ficción"],
  },
  {
    id: 11,
    year: 2023,
    title: "La Casa de los Espíritus",
    author: "Isabel Allende",
    rating: 4.6,
    totalLikes: 1600,
    coverImage: "https://m.media-amazon.com/images/I/71eX+IaH3AL._AC_SY679_.jpg",
    genre: ["Ficción", "Realismo Mágico"],
  },
  {
    id: 12,
    year: 2018,
    title: "El Psicoanalista",
    author: "John Katzenbach",
    rating: 4.4,
    totalLikes: 2200,
    coverImage: "https://m.media-amazon.com/images/I/41F3W3cY-EL._SX307_BO1,204,203,200_.jpg",
    genre: ["Thriller", "Psicológico"],
  },
  {
    id: 13,
    year: 2014,
    title: "Los Hombres que no Amaban a las Mujeres",
    author: "Stieg Larsson",
    rating: 4.7,
    totalLikes: 2400,
    coverImage: "https://m.media-amazon.com/images/I/51zFZkS9jLL._SX325_BO1,204,203,200_.jpg",
    genre: ["Misterio", "Thriller"],
  },
  {
    id: 14,
    year: 2020,
    title: "El Hobbit",
    author: "J.R.R. Tolkien",
    rating: 4.8,
    totalLikes: 3800,
    coverImage: "https://m.media-amazon.com/images/I/91OM6HTY7iL._AC_SY679_.jpg",
    genre: ["Fantasía", "Aventura"],
  },
  {
    id: 15,
    year: 2022,
    title: "Sapiens: De Animales a Dioses",
    author: "Yuval Noah Harari",
    rating: 4.5,
    totalLikes: 1500,
    coverImage: "https://m.media-amazon.com/images/I/71F3e6YZy9L._AC_SY679_.jpg",
    genre: ["Historia", "No Ficción"],
  },
  {
    id: 16,
    year: 2019,
    title: "El Secreto",
    author: "Rhonda Byrne",
    rating: 4.2,
    totalLikes: 1900,
    coverImage: "https://m.media-amazon.com/images/I/81m5D1T6yyL._AC_SY679_.jpg",
    genre: ["Autoayuda", "Filosofía"],
  },
  {
    id: 17,
    year: 2011,
    title: "La Chica del Tren",
    author: "Paula Hawkins",
    rating: 4.3,
    totalLikes: 2100,
    coverImage: "https://m.media-amazon.com/images/I/61drLTMh70L._AC_SY679_.jpg",
    genre: ["Thriller", "Psicológico"],
  },
  {
    id: 18,
    year: 2013,
    title: "Los Pilares de la Tierra",
    author: "Ken Follett",
    rating: 4.8,
    totalLikes: 3200,
    coverImage: "https://m.media-amazon.com/images/I/91ODVmnR-2L._AC_SY679_.jpg",
    genre: ["Histórico", "Drama"],
  },
  {
    id: 19,
    year: 2021,
    title: "La Amiga Estúpida",
    author: "Marta Carrasco",
    rating: 4.1,
    totalLikes: 1100,
    coverImage: "https://m.media-amazon.com/images/I/91o0-cPqlTL._AC_SY679_.jpg",
    genre: ["Ficción", "Humor"],
  },
  {
    id: 20,
    year: 2017,
    title: "La Chica de Nieve",
    author: "Javier Castillo",
    rating: 4.4,
    totalLikes: 1400,
    coverImage: "https://m.media-amazon.com/images/I/81n-VqRjlqL._AC_SY679_.jpg",
    genre: ["Misterio", "Thriller"],
  },
];
