export const genres = [
  "Fiction",
  "Classic",
  "Dystopian",
  "Science Fiction",
  "Romance",
  "Adventure",
  "Fantasy",
  "Coming-of-age",
  "Magical Realism",
  "Literary Fiction",
  "Historical Fiction",
  "Epic",
  "Mythology",
  "Poetry",
  "Philosophical Fiction",
  "Psychological Fiction",
  "Gothic",
  "Philosophical",
  "Satire",
];

export const authors = [
  "Harper Lee",
  "George Orwell",
  "Jane Austen",
  "F. Scott Fitzgerald",
  "Herman Melville",
  "J.R.R. Tolkien",
  "J.D. Salinger",
  "Gabriel Garcia Marquez",
  "Leo Tolstoy",
  "Homer",
  "Dante Alighieri",
  "Fyodor Dostoevsky",
  "Oscar Wilde",
  "Aldous Huxley",
  "Alexandre Dumas",
  "Paulo Coelho",
  "Mark Twain",
];

export const dummyBooks = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: 1960,
    genre: ["Fiction", "Classic"],
    description: "A classic novel depicting racial injustice in the American South.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    genre: ["Dystopian", "Science Fiction"],
    description: "A dystopian novel portraying a totalitarian society.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    genre: ["Classic", "Romance"],
    description: "A classic novel exploring themes of love, marriage, and social norms.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: 1925,
    genre: ["Fiction", "Classic"],
    description: "A tale of the American Dream, wealth, and love during the Roaring Twenties.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 5,
    title: "Moby-Dick",
    author: "Herman Melville",
    year: 1851,
    genre: ["Fiction", "Adventure"],
    description: "The epic tale of Captain Ahab's obsession with the white whale.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 6,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    genre: ["Fantasy", "Adventure"],
    description: "An epic fantasy saga about the quest to destroy the One Ring.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    year: 1951,
    genre: ["Fiction", "Coming-of-age"],
    description: "A classic coming-of-age novel following Holden Caulfield's journey.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    genre: ["Fantasy", "Adventure"],
    description: "The prequel to The Lord of the Rings, following Bilbo Baggins' journey.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 9,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    year: 1967,
    genre: ["Magical Realism", "Literary Fiction"],
    description: "A multi-generational saga of the Buendía family in the fictional town of Macondo.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 10,
    title: "War and Peace",
    author: "Leo Tolstoy",
    year: 1869,
    genre: ["Historical Fiction", "Epic"],
    description: "A monumental work depicting the events of Russian society during the Napoleonic era.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 11,
    title: "The Odyssey",
    author: "Homer",
    year: "8th century BCE",
    genre: ["Epic", "Mythology"],
    description: "An ancient Greek epic poem recounting Odysseus' ten-year journey home after the Trojan War.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 12,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    year: "1320",
    genre: ["Epic", "Poetry"],
    description: "An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 13,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    genre: ["Classic", "Philosophical Fiction"],
    description: "A complex novel exploring themes of spirituality, morality, and human nature.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 14,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    genre: ["Classic", "Psychological Fiction"],
    description: "A psychological thriller revolving around guilt, conscience, and redemption.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    year: 1890,
    genre: ["Gothic", "Philosophical Fiction"],
    description: "A novel about a man whose portrait ages while he retains his youth and beauty.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 16,
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    genre: ["Dystopian", "Science Fiction"],
    description: "A dystopian vision of a future society obsessed with pleasure and conformity.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 17,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    year: 1844,
    genre: ["Adventure", "Historical Fiction"],
    description: "An adventure novel of revenge, love, and redemption set in the early 19th century.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 18,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    year: 1877,
    genre: ["Classic", "Romance"],
    description: "A tragic love story set against the backdrop of Russian high society.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 19,
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: 1988,
    genre: ["Fiction", "Philosophical"],
    description: "A philosophical novel about a shepherd boy's journey to find his personal legend.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 20,
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: 1884,
    genre: ["Adventure", "Satire"],
    description: "A satirical novel following Huck Finn's journey down the Mississippi River.",
    coverImage: "https://fakeimg.pl/667x1000/cc6600",
  },
];
